language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - PEEWEE_VERSION=3.0.20
  - PEEWEE_VERSION=3.1.7
  - PEEWEE_VERSION=3.2.5
  - PEEWEE_VERSION=3.3.4
  - PEEWEE_VERSION=3.4.0
  - PEEWEE_VERSION=3.5.2
  - PEEWEE_VERSION=3.6.4
  - PEEWEE_VERSION=3.7.1
install:
  - "pip install peewee==$PEEWEE_VERSION"
  - "pip install python-coveralls==2.7.0"
  - "pip install -r requirements-test.txt"
before_script:
  - "coverage erase"
script:
  - "py.test --cov=peewee_moves.py"
after_success:
  - "coverage report"
  - "coveralls"
